[build]
  command = "npm run build --workspace client"
  publish = "client/dist"

[build.environment]
  BASE_PATH = "/"

[[redirects]]
  from = "https://www.ftbend-community-resources.netlify.app/*"
  to = "https://ftbend-community-resources.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.ftbend-community-resources.netlify.app/*"
  to = "https://ftbend-community-resources.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://ftbend-community-resources.netlify.app/*"
  to = "https://ftbend-community-resources.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://ftbend-community-resources-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
