[build]
  command = "npm run build --workspace client"
  publish = "client/dist"

[build.environment]
  BASE_PATH = "/"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
